"""initial

Revision ID: 21aac634989a
Revises: 
Create Date: 2026-04-21 21:22:51.216486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21aac634989a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(), nullable=True),
    sa.Column('record_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('performed_by', sa.String(), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_table_name'), 'audit_logs', ['table_name'], unique=False)
    op.create_table('guidelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('pdf_url', sa.String(), nullable=True),
    sa.Column('pdf_hash', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSED', 'FAILED', 'HUMAN_REVIEW', name='guidelinestatus'), nullable=True),
    sa.Column('raw_text_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guidelines_id'), 'guidelines', ['id'], unique=False)
    op.create_index(op.f('ix_guidelines_pdf_hash'), 'guidelines', ['pdf_hash'], unique=True)
    op.create_index(op.f('ix_guidelines_source'), 'guidelines', ['source'], unique=False)
    op.create_table('trials',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('sponsor_org_id', sa.String(), nullable=True),
    sa.Column('phase', sa.String(), nullable=True),
    sa.Column('indication', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('enrolled_count', sa.Integer(), nullable=True),
    sa.Column('sites_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trials_id'), 'trials', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('site_id', sa.String(), nullable=True),
    sa.Column('trial_ids', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('monitoring_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('trial_id', sa.String(), nullable=True),
    sa.Column('biomarker', sa.String(), nullable=True),
    sa.Column('operator', sa.String(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SUPERSEDED', 'PENDING', name='rulestatus'), nullable=True),
    sa.Column('diff_summary', sa.JSON(), nullable=True),
    sa.Column('source_guideline_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['source_guideline_id'], ['guidelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_rules_biomarker'), 'monitoring_rules', ['biomarker'], unique=False)
    op.create_index(op.f('ix_monitoring_rules_id'), 'monitoring_rules', ['id'], unique=False)
    op.create_index(op.f('ix_monitoring_rules_trial_id'), 'monitoring_rules', ['trial_id'], unique=False)
    op.create_table('trial_sites',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('trial_id', sa.String(), nullable=True),
    sa.Column('hospital_name', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('pi_user_id', sa.String(), nullable=True),
    sa.Column('patient_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trial_sites_id'), 'trial_sites', ['id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('trial_id', sa.String(), nullable=True),
    sa.Column('site_id', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['trial_sites.id'], ),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_external_id'), 'patients', ['external_id'], unique=True)
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_table('pv_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trial_id', sa.String(), nullable=True),
    sa.Column('triggered_by_guideline_id', sa.Integer(), nullable=True),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('severity_breakdown', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['monitoring_rules.id'], ),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.id'], ),
    sa.ForeignKeyConstraint(['triggered_by_guideline_id'], ['guidelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pv_reports_id'), 'pv_reports', ['id'], unique=False)
    op.create_table('biomarker_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=True),
    sa.Column('biomarker', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('quality_flag', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biomarker_readings_biomarker'), 'biomarker_readings', ['biomarker'], unique=False)
    op.create_index(op.f('ix_biomarker_readings_id'), 'biomarker_readings', ['id'], unique=False)
    op.create_index(op.f('ix_biomarker_readings_recorded_at'), 'biomarker_readings', ['recorded_at'], unique=False)
    op.create_table('patient_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=True),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('old_rule_id', sa.Integer(), nullable=True),
    sa.Column('old_status', sa.Enum('SAFE', 'AT_RISK', 'CRITICAL', 'BORDERLINE', 'INSUFFICIENT_DATA', name='evaluationstatus'), nullable=True),
    sa.Column('new_status', sa.Enum('SAFE', 'AT_RISK', 'CRITICAL', 'BORDERLINE', 'INSUFFICIENT_DATA', name='evaluationstatus'), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('flagged', sa.Boolean(), nullable=True),
    sa.Column('evaluation_triggered_by', sa.String(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['monitoring_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_evaluations_id'), 'patient_evaluations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_evaluations_id'), table_name='patient_evaluations')
    op.drop_table('patient_evaluations')
    op.drop_index(op.f('ix_biomarker_readings_recorded_at'), table_name='biomarker_readings')
    op.drop_index(op.f('ix_biomarker_readings_id'), table_name='biomarker_readings')
    op.drop_index(op.f('ix_biomarker_readings_biomarker'), table_name='biomarker_readings')
    op.drop_table('biomarker_readings')
    op.drop_index(op.f('ix_pv_reports_id'), table_name='pv_reports')
    op.drop_table('pv_reports')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_external_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_trial_sites_id'), table_name='trial_sites')
    op.drop_table('trial_sites')
    op.drop_index(op.f('ix_monitoring_rules_trial_id'), table_name='monitoring_rules')
    op.drop_index(op.f('ix_monitoring_rules_id'), table_name='monitoring_rules')
    op.drop_index(op.f('ix_monitoring_rules_biomarker'), table_name='monitoring_rules')
    op.drop_table('monitoring_rules')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_trials_id'), table_name='trials')
    op.drop_table('trials')
    op.drop_index(op.f('ix_guidelines_source'), table_name='guidelines')
    op.drop_index(op.f('ix_guidelines_pdf_hash'), table_name='guidelines')
    op.drop_index(op.f('ix_guidelines_id'), table_name='guidelines')
    op.drop_table('guidelines')
    op.drop_index(op.f('ix_audit_logs_table_name'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
